name: Spinarak bot

on:
  schedule:
    - cron: "*/5 * * * *"
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  run-spinarak:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Chrome
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt-get install -y ./google-chrome-stable_current_amd64.deb
      - name: Install dependencies
        run: |
          sudo apt-get update
          # font package needed for Japanese to render in captured screenshots
          sudo apt-get install -y fonts-noto-cjk unzip
          pip install --upgrade pip
          pip install chromedriver-autoinstaller selenium beautifulsoup4
      - name: Run Python Selenium script
        env:
          GMAIL_SENDER: ${{ secrets.GMAIL_SENDER }}
          GMAIL_APP_PW: ${{ secrets.GMAIL_APP_PW }}
          GMAIL_RECIPIENT: ${{ secrets.GMAIL_RECIPIENT }}
          GMAIL_RECIPIENT_2: ${{ secrets.GMAIL_RECIPIENT_2 }}
        run: |
          set -e
          echo -e "current NAT'd source IP address: `curl -s api.ipify.org`\n\n"
          python spinarak.py 2>&1
          ls -al

      - name: Check if there are any changes
        id: verify_diff
        run: |
          git diff --quiet . || echo "changed=true" >> $GITHUB_OUTPUT

      - name: Commit & push screenshot to repo
        if: steps.verify_diff.outputs.changed == 'true'
        run: |
          git config --global user.name '${{github.actor}}'
          git config --global user.email '${{github.actor}}@users.noreply.github.com'
          git add --all
          git commit -am "Screenshot(s)"
          #git pull
          git push --force
